name: Simple Jekyll Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Build
        run: bundle exec jekyll build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload
        uses: actions/upload-pages-artifact@v3

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3 